package com.uparu.uparumaking

object UparuRepository {

    val all: List<UparuInfo> = listOf(
        UparuInfo(
            profile = R.drawable.gogo,
            name = "고고",
            gold = 9,
            typeDrawable = R.drawable.typewinf,
            egg = R.drawable.eggwinf,
            typeText = "바람,불",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.godaesinyong,
            name = "고대신룡",
            gold = 53,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.egggodaesinyong,
            typeText = "빛",
            timeDisplay = "35시간57분",
            timeForSort = 35.95,
            sell = 5000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.godaesinyong22,
            name = "고대신룡S",
            gold = 53,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.egggodaesinyong,
            typeText = "빛",
            timeDisplay = "35시간57분",
            timeForSort = 35.95,
            sell = 5000000,
            isStar = true,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.godium,
            name = "고디움",
            gold = 15,
            typeDrawable = R.drawable.typefnwi,
            egg = R.drawable.egggodium,
            typeText = "불,바람",
            timeDisplay = "10시간57분",
            timeForSort = 10.95,
            sell = 1530000,
        ),
        UparuInfo(
            profile = R.drawable.goldi,
            name = "골디",
            gold = 53,
            typeDrawable = R.drawable.typegold,
            egg = R.drawable.egggoldi,
            typeText = "황금",
            timeDisplay = "48시간",
            timeForSort = 48.0,
            sell = 5000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.gururu,
            name = "구루루",
            gold = 8,
            typeDrawable = R.drawable.typewinl,
            egg = R.drawable.eggwinl,
            typeText = "바람,천둥",
            timeDisplay = "8시간30분",
            timeForSort = 8.5,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.giroro,
            name = "기로로",
            gold = 8,
            typeDrawable = R.drawable.typewinl,
            egg = R.drawable.eggwinl,
            typeText = "바람,천둥",
            timeDisplay = "8시간30분",
            timeForSort = 8.5,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.ggobu,
            name = "꼬부",
            gold = 8,
            typeDrawable = R.drawable.typewing,
            egg = R.drawable.eggwing,
            typeText = "바람,숲",
            timeDisplay = "8시간",
            timeForSort = 8.0,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.ggulsori,
            name = "꿀소리",
            gold = 7,
            typeDrawable = R.drawable.typewini,
            egg = R.drawable.eggggulsori,
            typeText = "바람,얼음",
            timeDisplay = "7시간45분",
            timeForSort = 7.75
        ),
        UparuInfo(
            profile = R.drawable.nyao,
            name = "냐오",
            gold = 9,
            typeDrawable = R.drawable.typelnwi,
            egg = R.drawable.eggnyao,
            typeText = "천둥,바람",
            timeDisplay = "8시간45분",
            timeForSort = 8.75,
            sell = 490000
        ),
        UparuInfo(
            profile = R.drawable.neoguru,
            name = "너구루",
            gold = 10,
            typeDrawable = R.drawable.typegrnm,
            egg = R.drawable.egggrnm,
            typeText = "땅,매직",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 400000
        ),
        UparuInfo(
            profile = R.drawable.nuni,
            name = "누니",
            gold = 18,
            typeDrawable = R.drawable.typeingrnwi,
            egg = R.drawable.eggnuni,
            typeText = "얼음,땅,바람",
            timeDisplay = "21시간",
            timeForSort = 21.0,
            sell = 1530000
        ),
        UparuInfo(
            profile = R.drawable.daram,
            name = "다람",
            gold = 7,
            typeDrawable = R.drawable.typefnl,
            egg = R.drawable.eggfnl,
            typeText = "불,천둥",
            timeDisplay = "4시간",
            timeForSort = 4.0,
            sell = 105000
        ),
        UparuInfo(
            profile = R.drawable.darkgoldi,
            name = "다크골디",
            gold = 55,
            typeDrawable = R.drawable.typegold,
            egg = R.drawable.egggoldi,
            typeText = "황금",
            timeDisplay = "48시간",
            timeForSort = 48.0,
            sell = 6000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.darknicks,
            name = "다크닉스",
            gold = 53,
            typeDrawable = R.drawable.typedark,
            egg = R.drawable.eggdarknicks,
            typeText = "어둠",
            timeDisplay = "35시간57분",
            timeForSort = 35.95,
            sell = 5000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.danbi,
            name = "단비",
            gold = 8,
            typeDrawable = R.drawable.typegrnf,
            egg = R.drawable.eggdanbi,
            typeText = "땅,불",
            timeDisplay = "9시간45분",
            timeForSort = 9.75,
            sell = 385000
        ),
        UparuInfo(
            profile = R.drawable.dalguru,
            name = "달구루",
            gold = 10,
            typeDrawable = R.drawable.typegnm,
            egg = R.drawable.egggnm,
            typeText = "숲,매직",
            timeDisplay = "8시간45분",
            timeForSort = 8.75,
            sell = 380000
        ),
        UparuInfo(
            profile = R.drawable.ducki,
            name = "덕키",
            gold = 12,
            typeDrawable = R.drawable.typemnwi,
            egg = R.drawable.eggmnwi,
            typeText = "매직,바람",
            timeDisplay = "11시간45분",
            timeForSort = 11.75
        ),
        UparuInfo(
            profile = R.drawable.dumpti,
            name = "덤프티",
            gold = 17,
            typeDrawable = R.drawable.typemnf,
            egg = R.drawable.eggdumpti,
            typeText = "매직,불",
            timeDisplay = "16시간",
            timeForSort = 16.0,
            sell = 1127000
        ),
        UparuInfo(
            profile = R.drawable.dodo,
            name = "도도",
            gold = 19,
            typeDrawable = R.drawable.typefnlnwi,
            egg = R.drawable.eggfnlnwi,
            typeText = "불,천둥,바람",
            timeDisplay = "23시간30분",
            timeForSort = 23.5,
            sell = 1530000
        ),
        UparuInfo(
            profile = R.drawable.dorong,
            name = "도롱",
            gold = 7,
            typeDrawable = R.drawable.typelng,
            egg = R.drawable.egglng,
            typeText = "천둥,숲",
            timeDisplay = "3시간30분",
            timeForSort = 3.5,
            sell = 55000
        ),
        UparuInfo(
            profile = R.drawable.dori,
            name = "도리",
            gold = 4,
            typeDrawable = R.drawable.typegrni,
            egg = R.drawable.egggrni,
            typeText = "땅,얼음",
            timeDisplay = "6시간",
            timeForSort = 6.0,
            sell = 150000
        ),
        UparuInfo(
            profile = R.drawable.doli,
            name = "돌리",
            gold = 7,
            typeDrawable = R.drawable.typeinwi,
            egg = R.drawable.egginwi,
            typeText = "얼음,바람",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.dolpi,
            name = "돌피",
            gold = 11,
            typeDrawable = R.drawable.typewanm,
            egg = R.drawable.eggwanm,
            typeText = "물,매직",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.donk,
            name = "동크",
            gold = 4,
            typeDrawable = R.drawable.typefngr,
            egg = R.drawable.eggfngr,
            typeText = "불,땅",
            timeDisplay = "3시간",
            timeForSort = 3.0,
            sell = 70000
        ),
        UparuInfo(
            profile = R.drawable.dudeoru,
            name = "두더루",
            gold = 4,
            typeDrawable = R.drawable.typeground,
            egg = R.drawable.egggr,
            typeText = "땅",
            timeDisplay = "3분",
            timeForSort = 0.05,
            sell = 50
        ),
        UparuInfo(
            profile = R.drawable.dudu,
            name = "두두",
            gold = 7,
            typeDrawable = R.drawable.typewini,
            egg = R.drawable.eggwini,
            typeText = "바람,얼음",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.dumurai,
            name = "두무라이",
            gold = 15,
            typeDrawable = R.drawable.typegrni,
            egg = R.drawable.eggdumurai,
            typeText = "땅,얼음",
            timeDisplay = "10시간15분",
            timeForSort = 10.25,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.dujangun,
            name = "듀장군",
            gold = 16,
            typeDrawable = R.drawable.typewanm,
            egg = R.drawable.eggdujangun,
            typeText = "물,매직",
            timeDisplay = "10시간15분",
            timeForSort = 10.25,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.dupa,
            name = "듀파",
            gold = 7,
            typeDrawable = R.drawable.typewater,
            egg = R.drawable.eggwa,
            typeText = "물",
            timeDisplay = "45분",
            timeForSort = 0.75,
            sell = 7500
        ),
        UparuInfo(
            profile = R.drawable.drapet,
            name = "드라펫",
            gold = 14,
            typeDrawable = R.drawable.typemnl,
            egg = R.drawable.eggdrapet,
            typeText = "매직,천둥",
            timeDisplay = "17시간30분",
            timeForSort = 17.5,
            sell = 770000
        ),
        UparuInfo(
            profile = R.drawable.ddoruru,
            name = "또루루",
            gold = 4,
            typeDrawable = R.drawable.typegngr,
            egg = R.drawable.egggngr,
            typeText = "숲,땅",
            timeDisplay = "30분",
            timeForSort = 0.5,
            sell = 500
        ),
        UparuInfo(
            profile = R.drawable.rairu,
            name = "라이루",
            gold = 6,
            typeDrawable = R.drawable.typelni,
            egg = R.drawable.egglni,
            typeText = "천둥,얼음",
            timeDisplay = "5시간",
            timeForSort = 5.0,
            sell = 392000
        ),
        UparuInfo(
            profile = R.drawable.raku,
            name = "라쿠",
            gold = 9,
            typeDrawable = R.drawable.typelnwi,
            egg = R.drawable.egglnwi,
            typeText = "천둥,바람",
            timeDisplay = "8시간45분",
            timeForSort = 8.75,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.raply,
            name = "라플리",
            gold = 5,
            typeDrawable = R.drawable.typefng,
            egg = R.drawable.eggfng,
            typeText = "불,숲",
            timeDisplay = "2시간30분",
            timeForSort = 2.5,
            sell = 343000
        ),
        UparuInfo(
            profile = R.drawable.rari,
            name = "래리",
            gold = 10,
            typeDrawable = R.drawable.typewangr,
            egg = R.drawable.eggrari,
            typeText = "물,땅",
            timeDisplay = "8시간",
            timeForSort = 8.0,
            sell = 360000
        ),
        UparuInfo(
            profile = R.drawable.rambert2,
            name = "램버트",
            gold = 25,
            typeDrawable = R.drawable.typewinwang,
            egg = R.drawable.eggrambert,
            typeText = "바람,물,숲",
            timeDisplay = "28시간",
            timeForSort = 28.0,
            sell = 1855000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.lovelove,
            name = "러브럽",
            gold = 16,
            typeDrawable = R.drawable.typelng,
            egg = R.drawable.egglove,
            typeText = "천둥,숲",
            timeDisplay = "10시간30분",
            timeForSort = 10.5,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.loveit2,
            name = "러빗",
            gold = 20,
            typeDrawable = R.drawable.typemninl,
            egg = R.drawable.eggloveit,
            typeText = "매직,얼음,천둥",
            timeDisplay = "28시간",
            timeForSort = 28.0,
            sell = 1850000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.resco,
            name = "레스코",
            gold = 18,
            typeDrawable = R.drawable.typegrnfnwa,
            egg = R.drawable.eggresco,
            typeText = "땅,불,물",
            timeDisplay = "23시간15분",
            timeForSort = 23.25,
            sell = 1530000
        ),
        UparuInfo(
            profile = R.drawable.reor,
            name = "레오르",
            gold = 26,
            typeDrawable = R.drawable.typegrnlnf,
            egg = R.drawable.eggreor,
            typeText = "땅,천둥,불",
            timeDisplay = "27시간15분",
            timeForSort = 27.25,
            sell = 1190000
        ),
        UparuInfo(
            profile = R.drawable.rey,
            name = "레이",
            gold = 35,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.eggrey,
            typeText = "빛",
            timeDisplay = "36시간",
            timeForSort = 36.0,
            sell = 4000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.remrem2,
            name = "렘렘",
            gold = 30,
            typeDrawable = R.drawable.typewaninm,
            egg = R.drawable.eggremrem,
            typeText = "물,얼음,매직",
            timeDisplay = "27시간",
            timeForSort = 27.0,
            sell = 2000000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.rodi,
            name = "로디",
            gold = 12,
            typeDrawable = R.drawable.typemnwi,
            egg = R.drawable.eggmnwi,
            typeText = "매직,바람",
            timeDisplay = "12시간15분",
            timeForSort = 12.25,
            sell = 600000
        ),
        UparuInfo(
            profile = R.drawable.roro,
            name = "로로",
            gold = 7,
            typeDrawable = R.drawable.typegnl,
            egg = R.drawable.egggnl,
            typeText = "숲,천둥",
            timeDisplay = "3시간45분",
            timeForSort = 3.75,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.rosa,
            name = "로사",
            gold = 18,
            typeDrawable = R.drawable.typewining,
            egg = R.drawable.eggwining,
            typeText = "바람,얼음,숲",
            timeDisplay = "22시간30분",
            timeForSort = 22.5,
            sell = 1350000
        ),
        UparuInfo(
            profile = R.drawable.rudol,
            name = "루돌",
            gold = 18,
            typeDrawable = R.drawable.typefning,
            egg = R.drawable.eggfning,
            typeText = "불,얼음,숲",
            timeDisplay = "24시간",
            timeForSort = 24.0,
            sell = 1500000
        ),
        UparuInfo(
            profile = R.drawable.rumion2,
            name = "루미온",
            gold = 42,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.eggrumion,
            typeText = "빛",
            timeDisplay = "40시간",
            timeForSort = 40.0,
            sell = 4500000,
            isStar = true,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.rupin,
            name = "루핀",
            gold = 42,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.eggrupin,
            typeText = "빛",
            timeDisplay = "40시간",
            timeForSort = 40.0,
            sell = 4500000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.marina,
            name = "마리나",
            gold = 11,
            typeDrawable = R.drawable.typewani,
            egg = R.drawable.eggwani,
            typeText = "물,얼음",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 551250
        ),
        UparuInfo(
            profile = R.drawable.myti2,
            name = "마이티",
            gold = 19,
            typeDrawable = R.drawable.typeinfnm,
            egg = R.drawable.eggmyti,
            typeText = "얼음,불,매직",
            timeDisplay = "29시간15분",
            timeForSort = 29.25,
            sell = 1750000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.magnus,
            name = "매그너스",
            gold = 300,
            typeDrawable = R.drawable.typecloud,
            egg = R.drawable.eggmagnus,
            typeText = "구름",
            timeDisplay = "50시간",
            timeForSort = 50.0,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.mendi,
            name = "맨디",
            gold = 10,
            typeDrawable = R.drawable.typewinf,
            egg = R.drawable.eggwinf,
            typeText = "바람,불",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.mushroom2,
            name = "머쉬룸",
            gold = 14,
            typeDrawable = R.drawable.typegrnf,
            egg = R.drawable.eggmushroom,
            typeText = "땅,불",
            timeDisplay = "10시간37분",
            timeForSort = 10.61,
            sell = 1350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.merry2,
            name = "메리",
            gold = 19,
            typeDrawable = R.drawable.typefngrng,
            egg = R.drawable.eggmerry,
            typeText = "불,땅,숲",
            timeDisplay = "22시간30분",
            timeForSort = 22.5,
            sell = 1530000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.meme,
            name = "메메",
            gold = 6,
            typeDrawable = R.drawable.typelnf,
            egg = R.drawable.egglnf,
            typeText = "천둥,불",
            timeDisplay = "4시간",
            timeForSort = 4.0,
            sell = 50000
        ),
        UparuInfo(
            profile = R.drawable.metoru,
            name = "메토루",
            gold = 10,
            typeDrawable = R.drawable.typemng,
            egg = R.drawable.eggmng,
            typeText = "매직,숲",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 490000
        ),
        UparuInfo(
            profile = R.drawable.mongkiru,
            name = "몽키루",
            gold = 6,
            typeDrawable = R.drawable.typelni,
            egg = R.drawable.egglni,
            typeText = "천둥,얼음",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.mumu,
            name = "무무",
            gold = 4,
            typeDrawable = R.drawable.typefngr,
            egg = R.drawable.eggfngr,
            typeText = "불,땅",
            timeDisplay = "3시간",
            timeForSort = 3.0,
            sell = 3000
        ),
        UparuInfo(
            profile = R.drawable.munguru,
            name = "뭉구루",
            gold = 4,
            typeDrawable = R.drawable.typegrng,
            egg = R.drawable.egggrng,
            typeText = "땅,숲",
            timeDisplay = "20분",
            timeForSort = 0.33,
            sell = 500
        ),
        UparuInfo(
            profile = R.drawable.mungchi,
            name = "뭉치",
            gold = 19,
            typeDrawable = R.drawable.typegrnmnl,
            egg = R.drawable.eggmungchi,
            typeText = "땅,매직,천둥",
            timeDisplay = "20시간30분",
            timeForSort = 20.5
        ),
        UparuInfo(
            profile = R.drawable.minidragon,
            name = "미니드래곤",
            gold = 14,
            typeDrawable = R.drawable.typegnwi,
            egg = R.drawable.eggminidragon,
            typeText = "숲,바람",
            timeDisplay = "11시간37분",
            timeForSort = 11.61,
            sell = 1710000
        ),
        UparuInfo(
            profile = R.drawable.mistic,
            name = "미스틱",
            gold = 200,
            typeDrawable = R.drawable.typecloud,
            egg = R.drawable.eggmistic,
            typeText = "구름",
            timeDisplay = "50시간",
            timeForSort = 50.0,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.miyo,
            name = "미요",
            gold = 7,
            typeDrawable = R.drawable.typeinwi,
            egg = R.drawable.eggmiyo,
            typeText = "얼음,바람",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.miko,
            name = "미코",
            gold = 10,
            typeDrawable = R.drawable.typewinf,
            egg = R.drawable.eggmiko,
            typeText = "바람,불",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.mingku,
            name = "밍쿠",
            gold = 13,
            typeDrawable = R.drawable.typemnl,
            egg = R.drawable.eggdrapet,
            typeText = "매직,천둥",
            timeDisplay = "11시간30분",
            timeForSort = 11.5,
            sell = 735000
        ),
        UparuInfo(
            profile = R.drawable.banaduck,
            name = "바나덕",
            gold = 9,
            typeDrawable = R.drawable.typegnl,
            egg = R.drawable.eggbanaduck,
            typeText = "숲,천둥",
            timeDisplay = "6시간",
            timeForSort = 6.0
        ),
        UparuInfo(
            profile = R.drawable.baretsa,
            name = "바렛사",
            gold = 8,
            typeDrawable = R.drawable.typefngr,
            egg = R.drawable.eggbaretsa,
            typeText = "불,땅",
            timeDisplay = "9시간45분",
            timeForSort = 9.75,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.bau,
            name = "바우",
            gold = 14,
            typeDrawable = R.drawable.typewingr,
            egg = R.drawable.eggwingr,
            typeText = "바람,땅",
            timeDisplay = "16시간",
            timeForSort = 16.0,
            sell = 1250000
        ),
        UparuInfo(
            profile = R.drawable.bamkuri,
            name = "밤쿠리",
            gold = 10,
            typeDrawable = R.drawable.typegrnm,
            egg = R.drawable.egggrnm,
            typeText = "땅,매직",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 400000
        ),
        UparuInfo(
            profile = R.drawable.beobi,
            name = "버비",
            gold = 5,
            typeDrawable = R.drawable.typegrng,
            egg = R.drawable.egggrng,
            typeText = "땅,숲",
            timeDisplay = "20분",
            timeForSort = 0.33,
            sell = 56000
        ),
        UparuInfo(
            profile = R.drawable.butterfin,
            name = "버터핀",
            gold = 5,
            typeDrawable = R.drawable.typegrnl,
            egg = R.drawable.egggrnl,
            typeText = "땅,천둥",
            timeDisplay = "6시간",
            timeForSort = 6.0,
            sell = 367500
        ),
        UparuInfo(
            profile = R.drawable.buffru,
            name = "버프루",
            gold = 8,
            typeDrawable = R.drawable.typegrnwa,
            egg = R.drawable.egggrnwa,
            typeText = "땅,물",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.berr2,
            name = "베르",
            gold = 26,
            typeDrawable = R.drawable.typewanwingr,
            egg = R.drawable.eggberr,
            typeText = "물,바람,땅",
            timeDisplay = "28시간30분",
            timeForSort = 28.5,
            sell = 1960000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.beild,
            name = "베일드",
            gold = 18,
            typeDrawable = R.drawable.typegrnwang,
            egg = R.drawable.eggbeild,
            typeText = "땅,물,숲",
            timeDisplay = "25시간15분",
            timeForSort = 24.5
        ),
        UparuInfo(
            profile = R.drawable.beti,
            name = "베티",
            gold = 6,
            typeDrawable = R.drawable.typeinl,
            egg = R.drawable.egginl,
            typeText = "얼음,천둥",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.betsi,
            name = "벳시",
            gold = 8,
            typeDrawable = R.drawable.typewanf,
            egg = R.drawable.eggbetsi,
            typeText = "물,불",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.boder,
            name = "보더",
            gold = 19,
            typeDrawable = R.drawable.typegnmnf,
            egg = R.drawable.eggboder,
            typeText = "숲,매직,불",
            timeDisplay = "25시간",
            timeForSort = 25.0
        ),
        UparuInfo(
            profile = R.drawable.boradoru,
            name = "보라도루",
            gold = 14,
            typeDrawable = R.drawable.typegrnwi,
            egg = R.drawable.egggrnwi,
            typeText = "땅,바람",
            timeDisplay = "16시간",
            timeForSort = 16.0,
            sell = 1250000
        ),
        UparuInfo(
            profile = R.drawable.bobo,
            name = "보보",
            gold = 10,
            typeDrawable = R.drawable.typewinwa,
            egg = R.drawable.eggwinwa,
            typeText = "바람,물",
            timeDisplay = "8시간15분",
            timeForSort = 8.25,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.bongbong,
            name = "봉봉",
            gold = 15,
            typeDrawable = R.drawable.typegni,
            egg = R.drawable.egggni,
            typeText = "숲,얼음",
            timeDisplay = "18시간",
            timeForSort = 18.0,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.blackapis2,
            name = "블랙아피스",
            gold = 80,
            typeDrawable = R.drawable.typedark,
            egg = R.drawable.eggblackapis,
            typeText = "어둠",
            timeDisplay = "47시간",
            timeForSort = 47.0,
            sell = 8250000,
            isStar = true,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.bibi,
            name = "비비",
            gold = 8,
            typeDrawable = R.drawable.typefnwa,
            egg = R.drawable.eggfnwa,
            typeText = "불,물",
            timeDisplay = "5시간",
            timeForSort = 5.0,
            sell = 55000
        ),
        UparuInfo(
            profile = R.drawable.bingo,
            name = "빙고",
            gold = 4,
            typeDrawable = R.drawable.typeingr,
            egg = R.drawable.eggingr,
            typeText = "얼음,땅",
            timeDisplay = "4시간45분",
            timeForSort = 4.75,
            sell = 25000
        ),
        UparuInfo(
            profile = R.drawable.bbururu,
            name = "뿌루루",
            gold = 6,
            typeDrawable = R.drawable.typefire,
            egg = R.drawable.eggf,
            typeText = "불",
            timeDisplay = "15분",
            timeForSort = 0.25,
            sell = 250
        ),
        UparuInfo(
            profile = R.drawable.samsam,
            name = "삼삼",
            gold = 7,
            typeDrawable = R.drawable.typegnl,
            egg = R.drawable.egggnl,
            typeText = "숲,천둥",
            timeDisplay = "3시간30분",
            timeForSort = 3.5,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.sechimi2,
            name = "새치미",
            gold = 30,
            typeDrawable = R.drawable.typeinwinf,
            egg = R.drawable.eggsechimi,
            typeText = "얼음,바람,불",
            timeDisplay = "27시간",
            timeForSort = 27.0,
            sell = 2000000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.shasha2,
            name = "샤샤",
            gold = 30,
            typeDrawable = R.drawable.typegrninl,
            egg = R.drawable.eggshasha,
            typeText = "땅,얼음,천둥",
            timeDisplay = "27시간",
            timeForSort = 27.0,
            sell = 2000000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.sharkgon2,
            name = "샤크곤",
            gold = 16,
            typeDrawable = R.drawable.typewani,
            egg = R.drawable.eggsharkgon,
            typeText = "물,얼음",
            timeDisplay = "10시간37분",
            timeForSort = 10.61,
            sell = 1350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.sharky,
            name = "샤키",
            gold = 11,
            typeDrawable = R.drawable.typewanm,
            egg = R.drawable.eggwanm,
            typeText = "물,매직",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.sufferyong2,
            name = "서퍼용",
            gold = 20,
            typeDrawable = R.drawable.typewanwinl,
            egg = R.drawable.eggsufferyong,
            typeText = "물,바람,천둥",
            timeDisplay = "25시간",
            timeForSort = 25.0,
            sell = 1850000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.softi,
            name = "소프티",
            gold = 13,
            typeDrawable = R.drawable.typeinm,
            egg = R.drawable.egginm,
            typeText = "얼음,매직",
            timeDisplay = "12시간45분",
            timeForSort = 12.75,
            sell = 624750
        ),
        UparuInfo(
            profile = R.drawable.suri,
            name = "수리",
            gold = 12,
            typeDrawable = R.drawable.typemnl,
            egg = R.drawable.eggmnl,
            typeText = "매직,천둥",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.shadow,
            name = "쉐도우",
            gold = 35,
            typeDrawable = R.drawable.typedark,
            egg = R.drawable.eggshadow,
            typeText = "어둠",
            timeDisplay = "36시간",
            timeForSort = 36.0,
            sell = 4000000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.shellru,
            name = "쉘루",
            gold = 18,
            typeDrawable = R.drawable.typewinwani,
            egg = R.drawable.eggwinwani,
            typeText = "바람,물,얼음",
            timeDisplay = "24시간30분",
            timeForSort = 24.5,
            sell = 1530000
        ),
        UparuInfo(
            profile = R.drawable.shujel,
            name = "슈젤",
            gold = 11,
            typeDrawable = R.drawable.typewanwi,
            egg = R.drawable.eggwanwi,
            typeText = "물,바람",
            timeDisplay = "12시간30분",
            timeForSort = 12.5,
            sell = 700000
        ),
        UparuInfo(
            profile = R.drawable.skulru2,
            name = "스컬루",
            gold = 23,
            typeDrawable = R.drawable.typelnwini,
            egg = R.drawable.eggskulru,
            typeText = "천둥,바람,얼음",
            timeDisplay = "25시간",
            timeForSort = 25.0,
            sell = 2000000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.skungki,
            name = "스컹키",
            gold = 7,
            typeDrawable = R.drawable.typewini,
            egg = R.drawable.eggwini,
            typeText = "바람,얼음",
            timeDisplay = "7시간",
            timeForSort = 7.0,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.scoti,
            name = "스코티",
            gold = 8,
            typeDrawable = R.drawable.typegrnf,
            egg = R.drawable.eggscoti,
            typeText = "땅,불",
            timeDisplay = "9시간45분",
            timeForSort = 9.75,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.stella2,
            name = "스텔라",
            gold = 55,
            typeDrawable = R.drawable.typelight,
            egg = R.drawable.eggstella,
            typeText = "빛",
            timeDisplay = "48시간",
            timeForSort = 48.0,
            sell = 5000000,
            isStar = true,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.sparumong2,
            name = "스파루몽",
            gold = 20,
            typeDrawable = R.drawable.typelnfni,
            egg = R.drawable.eggsparumong,
            typeText = "천둥,불,얼음",
            timeDisplay = "28시간45분",
            timeForSort = 28.75,
            sell = 1850000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.spain,
            name = "스파인",
            gold = 14,
            typeDrawable = R.drawable.typewinl,
            egg = R.drawable.eggspain,
            typeText = "바람,천둥",
            timeDisplay = "10시간37분",
            timeForSort = 10.61,
            sell = 1350000
        ),
        UparuInfo(
            profile = R.drawable.spain22,
            name = "스파인S",
            gold = 14,
            typeDrawable = R.drawable.typewinl,
            egg = R.drawable.eggspain,
            typeText = "바람,천둥",
            timeDisplay = "10시간37분",
            timeForSort = 10.61,
            sell = 1350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.seed,
            name = "시드",
            gold = 5,
            typeDrawable = R.drawable.typegnf,
            egg = R.drawable.egggnf,
            typeText = "숲,불",
            timeDisplay = "2시간30분",
            timeForSort = 2.5,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.silli,
            name = "실리",
            gold = 11,
            typeDrawable = R.drawable.typemnwa,
            egg = R.drawable.eggmnwa,
            typeText = "매직,물",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 696500
        ),
        UparuInfo(
            profile = R.drawable.armang,
            name = "아르망",
            gold = 8,
            typeDrawable = R.drawable.typegrnf,
            egg = R.drawable.egggrnf,
            typeText = "땅,불",
            timeDisplay = "9시간45분",
            timeForSort = 9.75,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.arki,
            name = "아르키",
            gold = 13,
            typeDrawable = R.drawable.typeinm,
            egg = R.drawable.eggarki,
            typeText = "얼음,매직",
            timeDisplay = "12시간45분",
            timeForSort = 12.75,
            sell = 624750
        ),
        UparuInfo(
            profile = R.drawable.alroha,
            name = "알로하",
            gold = 18,
            typeDrawable = R.drawable.typewaning,
            egg = R.drawable.eggalroha,
            typeText = "물,얼음,숲",
            timeDisplay = "22시간15분",
            timeForSort = 22.25,
            sell = 1487500
        ),
        UparuInfo(
            profile = R.drawable.ali,
            name = "알리",
            gold = 8,
            typeDrawable = R.drawable.typelng,
            egg = R.drawable.egglng,
            typeText = "천둥,숲",
            timeDisplay = "4시간15분",
            timeForSort = 4.25,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.alpha,
            name = "알파",
            gold = 17,
            typeDrawable = R.drawable.typefnm,
            egg = R.drawable.eggfnm,
            typeText = "불,매직",
            timeDisplay = "13시간",
            timeForSort = 13.0,
            sell = 1350000
        ),
        UparuInfo(
            profile = R.drawable.applechick,
            name = "애플칙",
            gold = 14,
            typeDrawable = R.drawable.typegngr,
            egg = R.drawable.eggapplechick,
            typeText = "숲,땅",
            timeDisplay = "9시간57분",
            timeForSort = 9.95,
            sell = 1250000
        ),
        UparuInfo(
            profile = R.drawable.applechick22,
            name = "애플칙S",
            gold = 16,
            typeDrawable = R.drawable.typegngr,
            egg = R.drawable.eggapplechick,
            typeText = "숲,땅",
            timeDisplay = "9시간57분",
            timeForSort = 9.95,
            sell = 1250000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.anti,
            name = "앤티",
            gold = 5,
            typeDrawable = R.drawable.typegngr,
            egg = R.drawable.egganti,
            typeText = "숲,땅",
            timeDisplay = "35분",
            timeForSort = 0.58,
            sell = 175000
        ),
        UparuInfo(
            profile = R.drawable.ebinu,
            name = "에비누",
            gold = 16,
            typeDrawable = R.drawable.typeinf,
            egg = R.drawable.eggebinu,
            typeText = "얼음,불",
            timeDisplay = "11시간15분",
            timeForSort = 11.25
        ),
        UparuInfo(
            profile = R.drawable.april,
            name = "에이프릴",
            gold = 31,
            typeDrawable = R.drawable.typegrnwini,
            egg = R.drawable.eggapril,
            typeText = "땅,바람,얼음",
            timeDisplay = "21시간",
            timeForSort = 21.0,
            sell = 1540000
        ),
        UparuInfo(
            profile = R.drawable.eli,
            name = "엘리",
            gold = 8,
            typeDrawable = R.drawable.typewangr,
            egg = R.drawable.eggwangr,
            typeText = "물,땅",
            timeDisplay = "7시간",
            timeForSort = 7.0,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.ogugu,
            name = "오구구",
            gold = 5,
            typeDrawable = R.drawable.typeingr,
            egg = R.drawable.eggogugu,
            typeText = "얼음,땅",
            timeDisplay = "5시간45분",
            timeForSort = 5.75,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.orpeus,
            name = "오르페우스",
            gold = 17,
            typeDrawable = R.drawable.typegrnl,
            egg = R.drawable.eggorpeus,
            typeText = "땅,천둥",
            timeDisplay = "11시간57분",
            timeForSort = 11.95,
            sell = 1890000
        ),
        UparuInfo(
            profile = R.drawable.omiyacon,
            name = "오미야콘",
            gold = 16,
            typeDrawable = R.drawable.typeingr,
            egg = R.drawable.eggomiyacon,
            typeText = "얼음,땅",
            timeDisplay = "11시간37분",
            timeForSort = 11.61,
            sell = 1710000
        ),
        UparuInfo(
            profile = R.drawable.wow,
            name = "와우",
            gold = 7,
            typeDrawable = R.drawable.typeinwi,
            egg = R.drawable.egginwi,
            typeText = "얼음,바람",
            timeDisplay = "7시간",
            timeForSort = 7.0,
            sell = 404250
        ),
        UparuInfo(
            profile = R.drawable.whyki,
            name = "와이키",
            gold = 18,
            typeDrawable = R.drawable.typewaninl,
            egg = R.drawable.eggwhyki,
            typeText = "물,얼음,천둥",
            timeDisplay = "22시간45분",
            timeForSort = 22.75,
            sell = 1487500
        ),
        UparuInfo(
            profile = R.drawable.warru,
            name = "왈루",
            gold = 11,
            typeDrawable = R.drawable.typeinwa,
            egg = R.drawable.egginwa,
            typeText = "얼음,물",
            timeDisplay = "11시간",
            timeForSort = 11.0,
            sell = 700000
        ),
        UparuInfo(
            profile = R.drawable.yongaru,
            name = "용가루",
            gold = 5,
            typeDrawable = R.drawable.typewind,
            egg = R.drawable.eggwi,
            typeText = "바람",
            timeDisplay = "5시간30분",
            timeForSort = 5.5,
            sell = 200000
        ),
        UparuInfo(
            profile = R.drawable.yongyong,
            name = "용용",
            gold = 5,
            typeDrawable = R.drawable.typegrnl,
            egg = R.drawable.egggrnl,
            typeText = "땅,천둥",
            timeDisplay = "6시간",
            timeForSort = 6.0,
            sell = 50000
        ),
        UparuInfo(
            profile = R.drawable.ururu,
            name = "우루루",
            gold = 8,
            typeDrawable = R.drawable.typelightning,
            egg = R.drawable.eggl,
            typeText = "천둥",
            timeDisplay = "2시간",
            timeForSort = 2.0,
            sell = 25000
        ),
        UparuInfo(
            profile = R.drawable.ukong,
            name = "우콩",
            gold = 19,
            typeDrawable = R.drawable.typegnmnl,
            egg = R.drawable.eggukong,
            typeText = "숲,매직,천둥",
            timeDisplay = "20시간30분",
            timeForSort = 20.5
        ),
        UparuInfo(
            profile = R.drawable.uparupa,
            name = "우파루파",
            gold = 7,
            typeDrawable = R.drawable.typegrnwa,
            egg = R.drawable.egggrnwa,
            typeText = "땅,물",
            timeDisplay = "7시간",
            timeForSort = 7.0,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.ulami,
            name = "울라미",
            gold = 5,
            typeDrawable = R.drawable.typeingr,
            egg = R.drawable.eggingr,
            typeText = "얼음,땅",
            timeDisplay = "5시간15분",
            timeForSort = 5.25,
            sell = 175000
        ),
        UparuInfo(
            profile = R.drawable.uli,
            name = "울리",
            gold = 7,
            typeDrawable = R.drawable.typeinwi,
            egg = R.drawable.egginwi,
            typeText = "얼음,바람",
            timeDisplay = "7시간",
            timeForSort = 7.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.ulfo,
            name = "울포",
            gold = 7,
            typeDrawable = R.drawable.typefnl,
            egg = R.drawable.eggulfo,
            typeText = "불,천둥",
            timeDisplay = "6시간30분",
            timeForSort = 6.5,
            sell = 280000
        ),
        UparuInfo(
            profile = R.drawable.wonderdragon,
            name = "원더드래곤",
            gold = 19,
            typeDrawable = R.drawable.typelnwinwa,
            egg = R.drawable.eggwonderdragon,
            typeText = "천둥,바람,물",
            timeDisplay = "20시간17분",
            timeForSort = 20.28,
            sell = 2070000
        ),
        UparuInfo(
            profile = R.drawable.yuni,
            name = "유니",
            gold = 15,
            typeDrawable = R.drawable.typeing,
            egg = R.drawable.egging,
            typeText = "얼음,숲",
            timeDisplay = "18시간",
            timeForSort = 18.0,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.yunipin,
            name = "유니핀",
            gold = 29,
            typeDrawable = R.drawable.typeinwanwi,
            egg = R.drawable.eggyunipin,
            typeText = "얼음,물,바람",
            timeDisplay = "24시간15분",
            timeForSort = 24.25
        ),
        UparuInfo(
            profile = R.drawable.yurion,
            name = "유리온",
            gold = 15,
            typeDrawable = R.drawable.typewani,
            egg = R.drawable.eggyurion,
            typeText = "물,얼음",
            timeDisplay = "11시간37분",
            timeForSort = 11.61,
            sell = 1710000
        ),
        UparuInfo(
            profile = R.drawable.jello,
            name = "젤로",
            gold = 10,
            typeDrawable = R.drawable.typemagic,
            egg = R.drawable.eggm,
            typeText = "매직",
            timeDisplay = "6시간30분",
            timeForSort = 6.5,
            sell = 250000
        ),
        UparuInfo(
            profile = R.drawable.jelisia,
            name = "젤리시아",
            gold = 19,
            typeDrawable = R.drawable.typemng,
            egg = R.drawable.eggjelisia,
            typeText = "매직,숲",
            timeDisplay = "10시간15분",
            timeForSort = 10.25,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.jurayong2,
            name = "쥬라용",
            gold = 20,
            typeDrawable = R.drawable.typegrnlng,
            egg = R.drawable.eggjurayong,
            typeText = "땅,천둥,숲",
            timeDisplay = "26시간30분",
            timeForSort = 26.5,
            sell = 1550000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.jjingyo,
            name = "찡요",
            gold = 8,
            typeDrawable = R.drawable.typewang,
            egg = R.drawable.eggwang,
            typeText = "물,숲",
            timeDisplay = "6시간",
            timeForSort = 6.0,
            sell = 210000
        ),
        UparuInfo(
            profile = R.drawable.chaupa,
            name = "차우파",
            gold = 30,
            typeDrawable = R.drawable.typegrnlnwa,
            egg = R.drawable.eggchaupa,
            typeText = "땅,천둥,물",
            timeDisplay = "25시간30분",
            timeForSort = 25.5
        ),
        UparuInfo(
            profile = R.drawable.chepy,
            name = "채피",
            gold = 16,
            typeDrawable = R.drawable.typeinf,
            egg = R.drawable.eggchepy,
            typeText = "얼음,불",
            timeDisplay = "14시간",
            timeForSort = 14.0,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.chao,
            name = "챠오",
            gold = 23,
            typeDrawable = R.drawable.typegnfni,
            egg = R.drawable.eggchao,
            typeText = "숲,불,얼음",
            timeDisplay = "24시간30분",
            timeForSort = 24.5
        ),
        UparuInfo(
            profile = R.drawable.chekiru,
            name = "체키루",
            gold = 18,
            typeDrawable = R.drawable.typegrninwa,
            egg = R.drawable.eggchekiru,
            typeText = "땅,얼음,물",
            timeDisplay = "23시간15분",
            timeForSort = 23.25,
            sell = 1960000
        ),
        UparuInfo(
            profile = R.drawable.chocolove,
            name = "초코럽",
            gold = 9,
            typeDrawable = R.drawable.typelng,
            egg = R.drawable.egglove,
            typeText = "천둥,숲",
            timeDisplay = "10시간30분",
            timeForSort = 10.5,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.chomchom,
            name = "촘촘",
            gold = 5,
            typeDrawable = R.drawable.typelngr,
            egg = R.drawable.egglngr,
            typeText = "천둥,땅",
            timeDisplay = "10시간",
            timeForSort = 10.0,
            sell = 385000
        ),
        UparuInfo(
            profile = R.drawable.chupa,
            name = "츄파",
            gold = 4,
            typeDrawable = R.drawable.typeice,
            egg = R.drawable.eggi,
            typeText = "얼음",
            timeDisplay = "4시간",
            timeForSort = 4.0,
            sell = 150000
        ),
        UparuInfo(
            profile = R.drawable.chupiking,
            name = "츄파이킹",
            gold = 15,
            typeDrawable = R.drawable.typeinwa,
            egg = R.drawable.eggchupiking,
            typeText = "얼음,물",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 1300000
        ),
        UparuInfo(
            profile = R.drawable.chichi,
            name = "치치",
            gold = 4,
            typeDrawable = R.drawable.typeingr,
            egg = R.drawable.eggingr,
            typeText = "얼음,땅",
            timeDisplay = "6시간",
            timeForSort = 6.0,
            sell = 150000
        ),
        UparuInfo(
            profile = R.drawable.capri,
            name = "카프리",
            gold = 32,
            typeDrawable = R.drawable.typemnwing,
            egg = R.drawable.eggcapri,
            typeText = "매직,바람,숲",
            timeDisplay = "27시간30분",
            timeForSort = 27.5,
            sell = 1960000
        ),
        UparuInfo(
            profile = R.drawable.copyru,
            name = "카피루",
            gold = 8,
            typeDrawable = R.drawable.typewangr,
            egg = R.drawable.eggwangr,
            typeText = "물,땅",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.caterfly,
            name = "캐터플라이",
            gold = 17,
            typeDrawable = R.drawable.typefnlng,
            egg = R.drawable.eggfnlng,
            typeText = "불,천둥,숲",
            timeDisplay = "23시간30분",
            timeForSort = 23.5,
            sell = 1190000
        ),
        UparuInfo(
            profile = R.drawable.candylove2,
            name = "캔디럽",
            gold = 10,
            typeDrawable = R.drawable.typeinl,
            egg = R.drawable.eggcandylove,
            typeText = "얼음,천둥",
            timeDisplay = "10시간30분",
            timeForSort = 10.5,
            sell = 350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.kogi,
            name = "코기",
            gold = 10,
            typeDrawable = R.drawable.typefnwi,
            egg = R.drawable.eggfnwi,
            typeText = "불,바람",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 428750
        ),
        UparuInfo(
            profile = R.drawable.koka,
            name = "코카",
            gold = 9,
            typeDrawable = R.drawable.typelngr,
            egg = R.drawable.egglngr,
            typeText = "천둥,땅",
            timeDisplay = "10시간",
            timeForSort = 10.0,
            sell = 200000
        ),
        UparuInfo(
            profile = R.drawable.cocolove,
            name = "코코럽",
            gold = 16,
            typeDrawable = R.drawable.typelng,
            egg = R.drawable.egglove,
            typeText = "천둥,숲",
            timeDisplay = "10시간30분",
            timeForSort = 10.5,
            sell = 245000
        ),
        UparuInfo(
            profile = R.drawable.koku,
            name = "코쿠",
            gold = 8,
            typeDrawable = R.drawable.typefnwa,
            egg = R.drawable.eggfnwa,
            typeText = "불,물",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.kota2,
            name = "코타",
            gold = 16,
            typeDrawable = R.drawable.typeinf,
            egg = R.drawable.egginf,
            typeText = "얼음,불",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.cuaca,
            name = "쿠아카",
            gold = 5,
            typeDrawable = R.drawable.typegngr,
            egg = R.drawable.eggcuaca,
            typeText = "숲,땅",
            timeDisplay = "35분",
            timeForSort = 0.58
        ),
        UparuInfo(
            profile = R.drawable.cupi2,
            name = "큐피",
            gold = 28,
            typeDrawable = R.drawable.typemnwinf,
            egg = R.drawable.eggcupi,
            typeText = "매직,바람,불",
            timeDisplay = "26시간",
            timeForSort = 26.0,
            sell = 2205000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.krang,
            name = "크랑",
            gold = 11,
            typeDrawable = R.drawable.typewanwi,
            egg = R.drawable.eggwanwi,
            typeText = "물,바람",
            timeDisplay = "12시간",
            timeForSort = 12.0,
            sell = 700000
        ),
        UparuInfo(
            profile = R.drawable.crapi,
            name = "크래피",
            gold = 10,
            typeDrawable = R.drawable.typegnwi,
            egg = R.drawable.egggnwi,
            typeText = "숲,바람",
            timeDisplay = "8시간",
            timeForSort = 8.0,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.cray,
            name = "크레이",
            gold = 15,
            typeDrawable = R.drawable.typelnwa,
            egg = R.drawable.egglnwa,
            typeText = "천둥,물",
            timeDisplay = "20시간",
            timeForSort = 20.0,
            sell = 1300000
        ),
        UparuInfo(
            profile = R.drawable.krono,
            name = "크로노",
            gold = 60,
            typeDrawable = R.drawable.typedark,
            egg = R.drawable.eggkrono,
            typeText = "어둠",
            timeDisplay = "42시간",
            timeForSort = 42.0,
            sell = 6500000,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.cropet,
            name = "크로펫",
            gold = 5,
            typeDrawable = R.drawable.typelngr,
            egg = R.drawable.eggcropet,
            typeText = "천둥,땅",
            timeDisplay = "10시간15분",
            timeForSort = 10.25,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.clau,
            name = "클라우",
            gold = 100,
            typeDrawable = R.drawable.typecloud,
            egg = R.drawable.eggclau,
            typeText = "구름",
            timeDisplay = "50시간",
            timeForSort = 50.0,
            isStar = true
        ),
        UparuInfo(
            profile = R.drawable.cline,
            name = "클리네",
            gold = 12,
            typeDrawable = R.drawable.typelnm,
            egg = R.drawable.eggcline,
            typeText = "천둥,매직",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 735000
        ),
        UparuInfo(
            profile = R.drawable.kitz,
            name = "키츠",
            gold = 7,
            typeDrawable = R.drawable.typelnwi,
            egg = R.drawable.eggkitz,
            typeText = "천둥,바람",
            timeDisplay = "8시간40분",
            timeForSort = 8.66,
            sell = 490000
        ),
        UparuInfo(
            profile = R.drawable.kickpig,
            name = "킥피그",
            gold = 17,
            typeDrawable = R.drawable.typefngnl,
            egg = R.drawable.eggkickpig,
            typeText = "불,숲,천둥",
            timeDisplay = "25시간45분",
            timeForSort = 25.75
        ),
        UparuInfo(
            profile = R.drawable.tamami,
            name = "타마미",
            gold = 6,
            typeDrawable = R.drawable.typeinl,
            egg = R.drawable.eggtamami,
            typeText = "얼음,천둥",
            timeDisplay = "5시간15분",
            timeForSort = 5.0,
            sell = 595000
        ),
        UparuInfo(
            profile = R.drawable.tenerpeng,
            name = "테너펭",
            gold = 13,
            typeDrawable = R.drawable.typeinwa,
            egg = R.drawable.egginwa,
            typeText = "얼음,물",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 612000
        ),
        UparuInfo(
            profile = R.drawable.tedi,
            name = "테디",
            gold = 10,
            typeDrawable = R.drawable.typemngr,
            egg = R.drawable.eggmngr,
            typeText = "매직,땅",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 400000
        ),
        UparuInfo(
            profile = R.drawable.tod,
            name = "토드",
            gold = 14,
            typeDrawable = R.drawable.typewanf,
            egg = R.drawable.eggwanf,
            typeText = "물,불",
            timeDisplay = "5시간",
            timeForSort = 5.0,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.toibo,
            name = "토이보",
            gold = 17,
            typeDrawable = R.drawable.typemnf,
            egg = R.drawable.eggmnf,
            typeText = "매직,불",
            timeDisplay = "13시간",
            timeForSort = 13.0,
            sell = 1127000
        ),
        UparuInfo(
            profile = R.drawable.toto,
            name = "토토",
            gold = 8,
            typeDrawable = R.drawable.typewanf,
            egg = R.drawable.eggwanf,
            typeText = "물,불",
            timeDisplay = "5시간",
            timeForSort = 5.0,
            sell = 125000
        ),
        UparuInfo(
            profile = R.drawable.totoru,
            name = "토토루",
            gold = 18,
            typeDrawable = R.drawable.typeingrnwi,
            egg = R.drawable.eggingrnwi,
            typeText = "얼음,땅,바람",
            timeDisplay = "21시간",
            timeForSort = 21.0,
            sell = 1530000
        ),
        UparuInfo(
            profile = R.drawable.tutu,
            name = "투투",
            gold = 8,
            typeDrawable = R.drawable.typewing,
            egg = R.drawable.eggwing,
            typeText = "바람,숲",
            timeDisplay = "8시간",
            timeForSort = 8.0,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.trumcat,
            name = "트럼캣",
            gold = 19,
            typeDrawable = R.drawable.typefnwinl,
            egg = R.drawable.eggtrumcat,
            typeText = "불,바람,천둥",
            timeDisplay = "26시간20분",
            timeForSort = 26.33
        ),
        UparuInfo(
            profile = R.drawable.tigo,
            name = "티고",
            gold = 7,
            typeDrawable = R.drawable.typeinwi,
            egg = R.drawable.egginwi,
            typeText = "얼음,바람",
            timeDisplay = "9시간",
            timeForSort = 9.0,
            sell = 420000
        ),
        UparuInfo(
            profile = R.drawable.tider,
            name = "티더",
            gold = 19,
            typeDrawable = R.drawable.typeingnwi,
            egg = R.drawable.eggtider,
            typeText = "얼음,숲,바람",
            timeDisplay = "22시간30분",
            timeForSort = 22.5,
            sell = 1350000
        ),
        UparuInfo(
            profile = R.drawable.tingklru,
            name = "팅클루",
            gold = 12,
            typeDrawable = R.drawable.typemnwi,
            egg = R.drawable.eggmnwi,
            typeText = "매직,바람",
            timeDisplay = "12시간15분",
            timeForSort = 12.25,
            sell = 600000
        ),
        UparuInfo(
            profile = R.drawable.firu,
            name = "파이루",
            gold = 10,
            typeDrawable = R.drawable.typefnwi,
            egg = R.drawable.eggfnwi,
            typeText = "불,바람",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.panpan,
            name = "판판",
            gold = 4,
            typeDrawable = R.drawable.typegrnf,
            egg = R.drawable.egggrnf,
            typeText = "땅,불",
            timeDisplay = "3시간",
            timeForSort = 3.0,
            sell = 15000
        ),
        UparuInfo(
            profile = R.drawable.pangpang2,
            name = "팡팡",
            gold = 19,
            typeDrawable = R.drawable.typewinmng,
            egg = R.drawable.eggpangpang,
            typeText = "바람,매직,숲",
            timeDisplay = "20시간17분",
            timeForSort = 20.28,
            sell = 2070000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.pandi,
            name = "팬디",
            gold = 12,
            typeDrawable = R.drawable.typewinm,
            egg = R.drawable.eggwinm,
            typeText = "바람,매직",
            timeDisplay = "12시간15분",
            timeForSort = 12.25,
            sell = 600000
        ),
        UparuInfo(
            profile = R.drawable.pumki2,
            name = "펌키",
            gold = 10,
            typeDrawable = R.drawable.typelnwi,
            egg = R.drawable.eggpumki,
            typeText = "천둥,바람",
            timeDisplay = "8시간30분",
            timeForSort = 8.5,
            sell = 350000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.pero,
            name = "페로",
            gold = 7,
            typeDrawable = R.drawable.typegnl,
            egg = R.drawable.egggnl,
            typeText = "숲,천둥",
            timeDisplay = "3시간30분",
            timeForSort = 3.5,
            sell = 40000
        ),
        UparuInfo(
            profile = R.drawable.pepe,
            name = "페페",
            gold = 7,
            typeDrawable = R.drawable.typefnl,
            egg = R.drawable.eggfnl,
            typeText = "불,천둥",
            timeDisplay = "4시간",
            timeForSort = 4.0,
            sell = 50000
        ),
        UparuInfo(
            profile = R.drawable.penriru,
            name = "펜리루",
            gold = 15,
            typeDrawable = R.drawable.typefni,
            egg = R.drawable.eggfni,
            typeText = "불,얼음",
            timeDisplay = "14시간",
            timeForSort = 14.0,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.penpen,
            name = "펜펜",
            gold = 13,
            typeDrawable = R.drawable.typemni,
            egg = R.drawable.eggmni,
            typeText = "매직,얼음",
            timeDisplay = "12시간45분",
            timeForSort = 12.75,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.pogisa,
            name = "포기사",
            gold = 15,
            typeDrawable = R.drawable.typegnf,
            egg = R.drawable.eggpogisa,
            typeText = "숲,불",
            timeDisplay = "10시간15분",
            timeForSort = 10.25,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.pori,
            name = "포리",
            gold = 10,
            typeDrawable = R.drawable.typegrass,
            egg = R.drawable.eggg,
            typeText = "숲",
            timeDisplay = "7초",
            timeForSort = 0.01,
            sell = 50
        ),
        UparuInfo(
            profile = R.drawable.poter,
            name = "포터",
            gold = 7,
            typeDrawable = R.drawable.typegnl,
            egg = R.drawable.egggnl,
            typeText = "숲,천둥",
            timeDisplay = "3시간30분",
            timeForSort = 3.5,
            sell = 140000
        ),
        UparuInfo(
            profile = R.drawable.photobi,
            name = "포토비",
            gold = 13,
            typeDrawable = R.drawable.typelnm,
            egg = R.drawable.eggphotobi,
            typeText = "천둥,매직",
            timeDisplay = "14시간30분",
            timeForSort = 14.5
        ),
        UparuInfo(
            profile = R.drawable.popomo,
            name = "포포모",
            gold = 19,
            typeDrawable = R.drawable.typefngnwa,
            egg = R.drawable.eggpopomo,
            typeText = "불,숲,물",
            timeDisplay = "20시간17분",
            timeForSort = 20.28,
            sell = 2070000
        ),
        UparuInfo(
            profile = R.drawable.foxy,
            name = "폭시",
            gold = 16,
            typeDrawable = R.drawable.typeinf,
            egg = R.drawable.egginf,
            typeText = "얼음,불",
            timeDisplay = "14시간",
            timeForSort = 14.0,
            sell = 550000
        ),
        UparuInfo(
            profile = R.drawable.polaru,
            name = "폴라루",
            gold = 14,
            typeDrawable = R.drawable.typeinwa,
            egg = R.drawable.egginwa,
            typeText = "얼음,물",
            timeDisplay = "11시간45분",
            timeForSort = 11.75,
            sell = 522000
        ),
        UparuInfo(
            profile = R.drawable.puddeok,
            name = "푸드덕",
            gold = 6,
            typeDrawable = R.drawable.typelnf,
            egg = R.drawable.egglnf,
            typeText = "천둥,불",
            timeDisplay = "4시간",
            timeForSort = 4.0,
            sell = 300000
        ),
        UparuInfo(
            profile = R.drawable.purni,
            name = "푸르니",
            gold = 17,
            typeDrawable = R.drawable.typegnwangr,
            egg = R.drawable.egggnwangr,
            typeText = "숲,물,땅",
            timeDisplay = "20시간15분",
            timeForSort = 20.25,
            sell = 1300000
        ),
        UparuInfo(
            profile = R.drawable.pus,
            name = "푸스",
            gold = 12,
            typeDrawable = R.drawable.typelnm,
            egg = R.drawable.egglnm,
            typeText = "천둥,매직",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 735000
        ),
        UparuInfo(
            profile = R.drawable.pupu,
            name = "푸푸",
            gold = 7,
            typeDrawable = R.drawable.typewang,
            egg = R.drawable.eggwang,
            typeText = "물,숲",
            timeDisplay = "4시간30분",
            timeForSort = 4.5,
            sell = 20000
        ),
        UparuInfo(
            profile = R.drawable.progu,
            name = "프로구",
            gold = 10,
            typeDrawable = R.drawable.typegnwa,
            egg = R.drawable.egggnwa,
            typeText = "숲,물",
            timeDisplay = "7시간45분",
            timeForSort = 7.75,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.pring,
            name = "프링",
            gold = 7,
            typeDrawable = R.drawable.typegnf,
            egg = R.drawable.egggnf,
            typeText = "숲,불",
            timeDisplay = "2시간30분",
            timeForSort = 2.5,
            sell = 3000
        ),
        UparuInfo(
            profile = R.drawable.flameru,
            name = "플라메루",
            gold = 10,
            typeDrawable = R.drawable.typefnwi,
            egg = R.drawable.eggflameru,
            typeText = "불,바람",
            timeDisplay = "9시간30분",
            timeForSort = 9.5,
            sell = 428750
        ),
        UparuInfo(
            profile = R.drawable.piguru,
            name = "피구루",
            gold = 10,
            typeDrawable = R.drawable.typegnwi,
            egg = R.drawable.egggnwi,
            typeText = "숲,바람",
            timeDisplay = "8시간",
            timeForSort = 8.0,
            sell = 350000
        ),
        UparuInfo(
            profile = R.drawable.pisingki,
            name = "피싱키",
            gold = 21,
            typeDrawable = R.drawable.typegninwi,
            egg = R.drawable.eggpisingki,
            typeText = "숲,얼음,바람",
            timeDisplay = "22시간30분",
            timeForSort = 22.5
        ),
        UparuInfo(
            profile = R.drawable.piko2,
            name = "피코",
            gold = 30,
            typeDrawable = R.drawable.typewangnl,
            egg = R.drawable.eggpiko,
            typeText = "물,숲,천둥",
            timeDisplay = "27시간",
            timeForSort = 27.0,
            sell = 2000000,
            isEvent = true
        ),
        UparuInfo(
            profile = R.drawable.piki,
            name = "피키",
            gold = 19,
            typeDrawable = R.drawable.typemngnl,
            egg = R.drawable.eggpiki,
            typeText = "매직,숲,천둥",
            timeDisplay = "20시간30분",
            timeForSort = 20.5,
            sell = 992250
        ),
        UparuInfo(
            profile = R.drawable.hakuru,
            name = "하쿠루",
            gold = 5,
            typeDrawable = R.drawable.typefng,
            egg = R.drawable.eggfng,
            typeText = "불,숲",
            timeDisplay = "2시간30분",
            timeForSort = 2.5,
            sell = 3000
        ),
        UparuInfo(
            profile = R.drawable.haerong,
            name = "해롱",
            gold = 8,
            typeDrawable = R.drawable.typegnwa,
            egg = R.drawable.egggnwa,
            typeText = "숲,물",
            timeDisplay = "4시간30분",
            timeForSort = 4.5,
            sell = 25000
        ),
        UparuInfo(
            profile = R.drawable.humpti,
            name = "험프티",
            gold = 12,
            typeDrawable = R.drawable.typemnl,
            egg = R.drawable.egghumpti,
            typeText = "매직,천둥",
            timeDisplay = "11시간15분",
            timeForSort = 11.25,
            sell = 500000
        ),
        UparuInfo(
            profile = R.drawable.hermi,
            name = "헤르미",
            gold = 15,
            typeDrawable = R.drawable.typelnwa,
            egg = R.drawable.egglnwa,
            typeText = "천둥,물",
            timeDisplay = "20시간",
            timeForSort = 20.0,
            sell = 1300000
        ),
        UparuInfo(
            profile = R.drawable.helsingpo,
            name = "헬싱포",
            gold = 18,
            typeDrawable = R.drawable.typefngrnwa,
            egg = R.drawable.egghelsingpo,
            typeText = "불,땅,물",
            timeDisplay = "26시간15분",
            timeForSort = 26.25
        ),
        UparuInfo(
            profile = R.drawable.hipopo,
            name = "히포포",
            gold = 8,
            typeDrawable = R.drawable.typewanf,
            egg = R.drawable.eggwanf,
            typeText = "물,불",
            timeDisplay = "7시간30분",
            timeForSort = 7.5,
            sell = 350000
        )
    )

    /** 별속성 포함 전부 (별속성O) */
    val star: List<UparuInfo>
        get() = all.filter { it.isStar }

    /** 이벤트/뽑기 포함 전부 (이벤트O) */
    val event: List<UparuInfo>
        get() = all.filter { it.isEvent }

    /** 조합에 쓸 우파루 (별속성X) */
    val nostar: List<UparuInfo>
        get() = all.filter { !it.isStar }

    /** 조합으로 나오는 우파루 (이벤트X) */
    val noevent: List<UparuInfo>
        get() = all.filter { !it.isEvent }

    fun findByName(name: String): UparuInfo? =
        all.firstOrNull { it.name == name }
}
